### ISSUE TITLE
docker build fail

### ISSUE THREAD

**Issue by yonggithub** [whoo/vscode-alpine#1]
Your project is great, but I met some problem from building the Dockerfile with command `docker build -t vscode .`.
![image](https://user-images.githubusercontent.com/25076827/153732897-01bf7ec0-814b-4170-9b28-adff2dde8f62.png)

**Comment by whoo** [comment]
sorry I'm not involve in yarn/installation process ... it works on my side.
Probably you should retry.

![image](https://user-images.githubusercontent.com/1499543/153966330-54f305ef-4e40-4cc6-b66c-df40ddadcdd5.png)

**Comment by yonggithub** [comment]
Thank you for your reply, I build success now. 
Can you open the Terminal on Code-server?
